apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.secretName" . }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
type: Opaque
data:
  # Base64 encoded secrets
  # To encode: echo -n 'your-value' | base64
  # To decode: echo 'encoded-value' | base64 -d
  DATABASE_URL: {{ .Values.secrets.databaseUrl | default "" | b64enc | quote }}
  JWT_SECRET_KEY: {{ .Values.secrets.jwtSecretKey | default "" | b64enc | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | default "" | b64enc | quote }}
